# This file was generated by GoReleaser. DO NOT EDIT.
cask "fumi" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "623c66725af0ce31a011138c938ff06265f698b8d7679d6cee403126db58f95d"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b02a8ce515b2f1214c1e3bce5d6e2c8e12923760198b56aa375bf5153fd987e0"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "fumi"
  desc "Browser × host machine integration utility"
  homepage "https://github.com/tkuramot/fumi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fumi"
  binary "fumi-host"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi-host"]
    end
  end

  # No zap stanza required

end
