# This file was generated by GoReleaser. DO NOT EDIT.
cask "fumi" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "cf2ed56ac336ec87249ecb913619c9d45aa34952c3f3dc6aa0925be1da57eacc"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25cf38672268941fc086575e527196c56fbf81aa07018a863db1eb59f5b2e403"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "fumi"
  desc "Browser × host machine integration utility"
  homepage "https://github.com/tkuramot/fumi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fumi"
  binary "fumi-host"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi-host"]
    end
  end

  # No zap stanza required

end
