# This file was generated by GoReleaser. DO NOT EDIT.
cask "fumi" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "e5c41b73ac43f6c27ac04185fd2b8bba2233d7ad014c0ac2c6025c62fa9c0f63"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "463ce441b624199eb05a34be5088ef13c7ee29137a36dbfec3cbf735df48ea51"
      url "https://github.com/tkuramot/fumi/releases/download/v#{version}/fumi_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "fumi"
  desc "Browser × host machine integration utility"
  homepage "https://github.com/tkuramot/fumi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fumi"
  binary "fumi-host"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fumi-host"]
    end
  end

  # No zap stanza required

end
