# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxrun" do
  version "0.11.5"

  on_macos do
    on_intel do
      sha256 "837f9f6a6e73bde1aacc019a0441469673b5a669a48cbb6f3ed3d3d6113e8595"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b07431bff51ea338dd300cbd3aabc903c527c0daeb45763caa95b1280f3e4727"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92f5229b241786f49f135dcbb1366071766ec8b3f7a90270ba7a1384bfcc28ac"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a262481d00e2d6b540df95079350457462cef34e2fdb2284f89ee1a17d9be232"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "muxrun"
  desc "Launch and manage multiple applications in groups using tmux"
  homepage "https://github.com/tkuramot/muxrun"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "muxrun"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxrun"]
    end
  end

  # No zap stanza required

end
