# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxrun" do
  version "0.11.7"

  on_macos do
    on_intel do
      sha256 "1d293756d44d5b5d8750d75be880ce3ec2dc5cecb1bc56a3e23be8cdef3e120a"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "48cf6ab8cbdda71a47ef7ff9b51d5a38d0bcf225c716f18e449983a10975776f"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27d08faad04700b61236da684ad62e25b8798de02e54f389bffc6603ea856c72"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e49eb3d47132fb370cc327d13df67afc63cc0f24583cc79aeaad9498ae6a772"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "muxrun"
  desc "Launch and manage multiple applications in groups using tmux"
  homepage "https://github.com/tkuramot/muxrun"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "muxrun"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxrun"]
    end
  end

  # No zap stanza required

end
