# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxrun" do
  version "0.11.2"

  on_macos do
    on_intel do
      sha256 "482ac4f0efacb45f657fd61bd1a531d5504fe642174dcac1401b577f4eda17fd"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8640ea23902bb92dca97fc252105f0359bb8690e97981c51b03da6b6f5dbccb3"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f06809b1776b10b0af04cf7bd87536528ef67cec7a58db075a26ba386ac225a"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "161ab91097e5dc0c1503e45217958402072c598738387f6def3c81a1e549dc7d"
      url "https://github.com/tkuramot/muxrun/releases/download/v#{version}/muxrun_#{version}_linux_arm64.tar.gz"
    end
  end

  name "muxrun"
  desc "Launch and manage multiple applications in groups using tmux"
  homepage "https://github.com/tkuramot/muxrun"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "muxrun"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxrun"]
    end
  end

  # No zap stanza required

end
