# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxrun < Formula
  desc "Launch and manage multiple applications in groups using tmux"
  homepage "https://github.com/tkuramot/muxrun"
  version "0.11.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tkuramot/muxrun/releases/download/v0.11.1/muxrun_0.11.1_darwin_amd64.tar.gz"
      sha256 "0e574f96b218703c2385a9b8a5c2b7dfdf0fea918267f35c2b7be43a1eed7a0d"

      define_method(:install) do
        bin.install "muxrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tkuramot/muxrun/releases/download/v0.11.1/muxrun_0.11.1_darwin_arm64.tar.gz"
      sha256 "0c119daf5250e56d2cecf2597ea38af247e19fbbfb89ed1b62f24cf9585751b4"

      define_method(:install) do
        bin.install "muxrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkuramot/muxrun/releases/download/v0.11.1/muxrun_0.11.1_linux_amd64.tar.gz"
      sha256 "dcb0a43da1e4900fba626f67a65b8b46e173c55c9d9ddead35375088f5de4799"
      define_method(:install) do
        bin.install "muxrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkuramot/muxrun/releases/download/v0.11.1/muxrun_0.11.1_linux_arm64.tar.gz"
      sha256 "38254ed8d87590311cc191f4522d091b27eb87c72908d8331ee3f73f4bf7b9f2"
      define_method(:install) do
        bin.install "muxrun"
      end
    end
  end

  test do
    system "#{bin}/muxrun", "--version"
  end
end
